AWSTemplateFormatVersion: '2010-09-09'
Description: S3 Static Website Hosting for Portfolio

Parameters:
  PortfolioBucketName:
    Type: String
    Description: Enter a globally unique name for your S3 bucket (e.g., portfolio-yourname-2024)
  DBName:
    Type: String
    Description: Enter a name for your DynamoDB table (e.g., PortfolioVisitorCount)

Resources:
  MyPortfolioBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref PortfolioBucketName
      WebsiteConfiguration:
        IndexDocument: index.html
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false

  MyBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref MyPortfolioBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: PublicReadForGetBucketObjects
            Effect: Allow
            Principal: '*'
            Action: 's3:GetObject'
            Resource: !Sub 'arn:aws:s3:::${MyPortfolioBucket}/*'

  MyCloudFront:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        DefaultRootObject: index.html
        DefaultCacheBehavior: 
          TargetOriginId: S3Origin
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods:
            - GET
            - HEAD
          ForwardedValues:
            QueryString: false
            Cookies:
              Forward: none
          DefaultTTL: 60
        ViewerCertificate:
          CloudFrontDefaultCertificate: true  
        Origins:
          - Id: S3Origin
            DomainName: !Select [2, !Split ['/', !GetAtt MyPortfolioBucket.WebsiteURL]]
            CustomOriginConfig:
              OriginProtocolPolicy: http-only
  MyDynamoTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      TableName: !Ref DBName
      BillingMode: PAY_PER_REQUEST

  MyLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: DynamoDBAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:GetItem
                  - dynamodb:UpdateItem
                  - dynamodb:PutItem
                Resource: !GetAtt MyDynamoDBTable.Arn
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: '*'

  MyVisitorCounterFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: VisitorCounter
      Runtime: python3.9
      Handler: index.lambda_handler
      Role: !GetAtt MyLambdaRole.Arn
      Code:
        ZipFile: |
          import json
          import boto3
          
          dynamodb = boto3.resource('dynamodb')
          table = dynamodb.Table('PortfolioVisitorCount')
          
          def lambda_handler(event, context):
              response = table.update_item(
                  Key={'id': 'count'},
                  UpdateExpression='SET visitors = visitors + :val',
                  ExpressionAttributeValues={':val': 1},
                  ReturnValues='UPDATED_NEW'
              )
              
              visitor_count = int(response['Attributes']['visitors'])
              
              return {
                  'statusCode': 200,
                  'headers': {
                      'Access-Control-Allow-Origin': '*',
                      'Access-Control-Allow-Headers': 'Content-Type',
                      'Access-Control-Allow-Methods': 'OPTIONS,POST,GET'
                  },
                  'body': json.dumps({'count': visitor_count})
              }
    
Outputs:
  WebsiteURL:
    Value: !GetAtt MyPortfolioBucket.WebsiteURL
    Description: URL for website hosted on S3
  CloudFrontURL:
    Value: !Sub 'https://${MyCloudFront.DomainName}'
    Description: Secure URL via CloudFront